spring.application.name=spring-boot-lab-app
http.logger.enabled=true
http.logger.include-request-body=true
http.logger.include-response-body=true

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %X{correlationId} %logger{36} - %msg%n